Update to Gleam 1.6.0 (#34)
* Use grapheme clusters to get string width

* changelog

* Replace constructor with builder function

* Clippy

* Replace String with EcoString

* String -> EcoString

* nix: convert strings to EcoStrings

* style: simplify string formatting for readability

* fix: formatting in `compiler-core/src/`

* Initial implementation of context-aware type printing for LSP hover

* Add tests for qualified type hover

* Fix printing of unbound type variables

* Print names of type variables on hover

* Merge `TypeNames` and `ValueNames` structs

* Properly print types when an alias is imported

* Correctly qualify shadowed prelude types

* Print underlying type when hovering a type alias

* Don't print aliases with type parameters

* Correctly print prelude types when shadowed by an alias of a non-named type

* Address review comments

* Remove special case for prelude types

* Evict prelude types from names when shadowed

* Fix Windows escaping

Closes gleam-lang/gleam/issues/3648

* Update changelog for v1.5.1

* Use a BiMap for constructor names

* Print qualified type names for type errors

* fix: erlang compiler bug with shadowing sized values in bit patterns

* CLI: Add javascript as option for template flag to `new` (#3395)

* use nix target in tests

* Update deps

* suggest to pattern match on result value

* Add snapshot

* clippy!

* cleanup code related to try expressions

* fix #3643

* changelog!

* Add BitArray constructor to the JS prelude types

* fix code generation

* changelog

* Rename variable

* skip optional dependencies

Signed-off-by: Gustavo Inacio <incio.gusta@gmail.com>

* use constraints if added again

Signed-off-by: Gustavo Inacio <incio.gusta@gmail.com>

* add incompatible optional deps test

Signed-off-by: Gustavo Inacio <incio.gusta@gmail.com>

* Implement code action to add type annotations

* Fix invalid TypeScript definitions for opaque types that use a private type

* add beam_compiler impl and trait, update gleam@@compile.erl script

* implement BeamCompiler trait for all file systems

* use the new BeamCompiler, fixup trait bounds

* make sure we notice when the compile script exits while we wait

* don't kill the beam compiler process  to make sure  files are properly written to disk

* rename functions, use a string literal for the unit separator, replace erlang:display with explicit io:put_chars

* move beam_compiler and gleam@@compile template to compiler-cli

* fix beam compiler import to glistix-core

* update CHANGELOG.md

* More unique string

* pass arguments as an erlang term

* cargo fmt

* fix changelog

* Note symlink issue on Windows

* Changes!

* Fix prelude re-export in generated TypeScript definitions

* Fix bug with labelled argument order

* Add tests for Erlang and Javascript

* add nix test for labelled function argument order

* Rust 1.82.0

* feat: action to convert qualified to unqualified

* half done

* seem work fine!

* work but fail at test?

* test done!

* chore:clean up

* chore: formatting

* feat: multi-editing work

* refactor logic

* feat: support pattern constructor

* chore: cleanup

* chore: rm some comments

* rm renamed test

* refactor: two pass traverse

* chore:more tests

* chore: add complex pattern test

* chore: update changelog

* Fix TS definitions when importing type aliases that reference unimported modules

* Remove unused `allow(clippy::arc_with_non_send_sync)`

* More consistent colouring of runtime errors on Erlang

* Don't remove the first argument in piped functions when it has a label

* fix: better deprecated error message

* changelog!

* fix-3720

* Fix compiler crash on duplicate fields

* Change error location

* Fix error message flipping 'expected' and 'found' type for values in a pipe

* Add test for showing correct error message when using values in a pipe

* Simplify error handling in pipe type checking

* Update changelog

* Return error from WASM compiler when unsupported features are used

* Fix Changelog

* Code action to add annotations to anonymous function

* Add test for nested `let`

* Clippy

* Change function literal kind tracking

* feat: unqualified to qualified import

* add test for unqualified to qualified import

* fix: temporary resolve same name issue

* fix: fix discarded import

* chore: more tests

* refactor logic

* cleanup

* chore: more tests

* chore: switch to ref

* Fix rebase

* fix spelling of UpdateMultiConstructorType error message

* Snapshot!

* Do not include dev deps in .app

* fix test helpers for glistix

* Resolve runtime type error

* Relative paths

* Windows

* Clippy

* Correct mistake

* Licence

* Add source code to warning snapshots

* Add source code to javascript tests

* Add source code to erlang snapshots

* Add source code to error snapshots

* Add source code to missing error snapshots

* Add source code to one more snapshot case

* fix makefile phony

* Rename function

* Add other module source code to snapshots

* support updating specific packages and their deps

* refactor based on review comments

* fix tests

* remove unnecessary test for circular deps

* updated changelog

* satisfy rust formatter

* unlocks specified packages and their unique dependencies

* compact the tests

* cargo fmt

* Extract variable part

* Optimise bit array creation in the JavaScript prelude

* Add more tests for toBitArray() in the JavaScript prelude

* Update changelog

* Reject invalid record construction

* Re-enable test

* fix: check if constructor exist when offer unqualify action

* changelog!

* add same test for type

* small fix

* replace is_type with ast::Layer

* refactor: replace "spread" with "record update" naming (gh-3737)

* nix: fix record update

* Fix bug with type alias printing

* Clippy

* fix hover hints for list tail

* CHANGELOG!

* Fix bug with anonymous function annotations

* Accept snapshot

* Update deps

* Update action

* Disable bot labels

* Update deps

* Initial implementation of record updates for known constructors

* Properly pass on type information when pattern matching

* Clippy + Changelog

* Disallow record updates when the variant can be one of several

* Improve error message when updating a known constructor

* Add known record fields to completions

* Rename `constructor_index` and document it

* Renaming

* Renaming

* Rename and reword errors

* Add more type-narrowing capabilities

* Prevent type narrowing escaping case expression guards

* Clarify Changelog

* Add tests to ensure inference is preserved

* Remove newline

* Update error snapshot format

* Fully explain variant narrowing in changelog

* Add more type-narrowing tests

* Implement exhaustiveness checking for type narrowing

* Fix changes after refactor

* Add feature tracking

* Improve warning for type narrowing in version constraints

* Change wording

* Reword changelog

* Reword errors and warnings

* Reword changelog

Also flatten logic in this helper function.

* Add optional repository.path config to gleam.toml

* Warn about unsafe integer values on JavaScript

* add 'int_value' to nix target

* fix constructor function in guard

* Don't offer Add Annotations code action for generated assignments

* Use `AssignmentKind::Generated` instead

* track shorthand label feature usage inside record updates

* update CHANGELOG.md

* typo

* Skip existing files when skip git option is enable

even with the --skip-git option the CLI ask to remove the files

tests ensure we can skip files that are none or without content:

```
---- new::tests::skip_existing_git_files_when_skip_git_is_true stdout ----
thread 'new::tests::skip_existing_git_files_when_skip_git_is_true' panicked at compiler-cli/src/new/tests.rs:321:6:
called `Result::unwrap()` on an `Err` value: OutputFilesAlreadyExist { file_names: ["/tmp/.tmpRvY1Nb/my_project/.gitignore"] }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

* Fix bug with duplicate labels in record update

* chore: improve file create in case of error

follow up on gleam-lang/gleam/pull/3787#pullrequestreview-2415286300

* Warn about unsafe integers in bit array patterns on JavaScript

* Fix several issues with negative Int values in bit arrays on JavaScript

* fix #3796

* changelog

* Fix bug with variant inference in tuples

* Add more tests and fix bug with `fn`

* Fix typos in the changelog

* fix #3804

* changelog

* failing test

* v1.6.0-rc1

* escape property names with special meaning on JavaScript

fix #3813

* also escape properties in record_access

* escape properties in guards and patterns as well

* Fix invalid toml example in changelog

* Fix incorrect warning about unsafe ints on JS when there's an @external

* delete cached metadata if a module is stale because of it's dependencies

fix #3772

* add test

* actually test the right thing

* Specify Erlang v27 in the CI workflow for new projects

* fix: more helpful error message in BuildLock::lock

fix: more helpful error message when locking build dir

fix: more helpful error message in BuildLock::lock

chore: style changes

* Format

* Changes!

* v1.6.0-rc2

* Scratch

* use glistix in scratch container

* fix bug with lsp completions

* CHANGELOG!

* Fix changelog

* v1.6.0

* fix test names

* Add source code to nix tests

* Add source code to Nix error snapshots

* Add source code to Nix module import snapshots

* update compiler-cli::new snapshots

* update RELEASE.md to mention compiler-cli::new tests

* update parse tests

* fix source code in nix tests added to wrong test type

* fix constructor function in nix guards

* bump compiler version constant

* update glistix builder source paths and hash

* clippy fixes

* set cli::new default target to nix

* format

---------

Signed-off-by: Gustavo Inacio <incio.gusta@gmail.com>
Co-authored-by: Giacomo Cavalieri <giacomo.cavalieri@icloud.com>
Co-authored-by: Hamir Mahal <hamirmahal@gmail.com>
Co-authored-by: GearsDatapacks <surya@seriousinfinitude.com>
Co-authored-by: Louis Pilfold <louis@lpil.uk>
Co-authored-by: Antonio Iaccarino <antonio.iaccarino@gmail.com>
Co-authored-by: Tar-Tarus <loubia314@gmail.com>
Co-authored-by: Richard Viney <richard.viney@gmail.com>
Co-authored-by: Gustavo Inacio <incio.gusta@gmail.com>
Co-authored-by: Joshua Reusch <jreusch4@gmail.com>
Co-authored-by: Frank Wang <1454884738@qq.com>
Co-authored-by: Markus Pettersson <markus.pettersson@mullvad.net>
Co-authored-by: BlockListed <44610569+BlockListed@users.noreply.github.com>
Co-authored-by: Jason Sipula <jason@fluximus.com>
Co-authored-by: George Grec <grec.george@protonmail.com>
Co-authored-by: Gears <40563462+GearsDatapacks@users.noreply.github.com>
Co-authored-by: Laurent Arnoud <laurent.arnoud@platform.sh>
Co-authored-by: TheShmill <21013808+TheShmill@users.noreply.github.com>
Co-authored-by: ZakFarmer <zak@perihelia.io>