Skip existing files when skip git option is enable
even with the --skip-git option the CLI ask to remove the files

tests ensure we can skip files that are none or without content:

```
---- new::tests::skip_existing_git_files_when_skip_git_is_true stdout ----
thread 'new::tests::skip_existing_git_files_when_skip_git_is_true' panicked at compiler-cli/src/new/tests.rs:321:6:
called `Result::unwrap()` on an `Err` value: OutputFilesAlreadyExist { file_names: ["/tmp/.tmpRvY1Nb/my_project/.gitignore"] }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```